///////////////////////////////////////////////////////////////////////////// 
//
//  By using this code, you are agreeing to the terms and conditions of 
//  the License Agreement included in the documentation for this code. 
// 
//  AUTODESK MAKES NO WARRANTIES, EXPRESS OR IMPLIED, AS TO THE CORRECTNESS 
//  OF THIS CODE OR ANY DERIVATIVE WORKS WHICH INCORPORATE IT. AUTODESK 
//  PROVIDES THE CODE ON AN "AS-IS" BASIS AND EXPLICITLY DISCLAIMS ANY 
//  LIABILITY, INCLUDING CONSEQUENTIAL AND INCIDENTAL DAMAGES FOR ERRORS, 
//  OMISSIONS, AND OTHER PROBLEMS IN THE CODE. 
// 
//  Use, duplication, or disclosure by the U.S. Government is subject to 
//  restrictions set forth in FAR 52.227-19 (Commercial Computer Software 
//  Restricted Rights) and DFAR 252.227-7013(c)(1)(ii) (Rights in Technical 
//  Data and Computer Software), as applicable. 

var ADSKDLMResourceStrings =
	{
		'en-US':{
		installInstHeader:'Installation Instructions',
		installStep1:'When shown the "Save or Run File" dialog, choose "Run"',
		installStep2:'Follow the steps in the setup wizard.',
		installStep3:'If you receive a browser warning, choose "Allow" (we also recommend turning off this warning for future downloads from Autodesk).',
		installStep4:'Autodesk Download Manager is now ready and will automatically begin delivering your selection.',
		installFooter:'Having problems? <a href="http://www.autodesk.com/">Manually start the download</a>',
		installInstMessage: 'This download needs to install the Autodesk Download Manager utility. Complete the following steps to download and run the small utility to proceed.',
		installUpgmessage: 'A new version of Autodesk Download Manager needs to be installed. Complete the following steps to download and run the small update to proceed.',
		installAdditionalInfo: 'Additional Information',
		installUpgHeader: 'Upgrade Instructions',

		helpDecideHeader: 'Help me decide a download type',
		helpDecideInstallNowHeader: 'Install Now',
		helpDecideInstallNowTitle1: 'Benefits',
		helpDecideInstallNowDesc1: 'The best way to get up and running quickly on this computer, with download and install in less than 1/2 the time of a Browser Download and subsequent Installation. Offers product selection prior to download, high compression, and automatic download resumption after connection interruptions.',
		helpDecideInstallNowTitle2: 'Whats Happens',
		helpDecideInstallNowDesc2: 'The Installer starts immediately and downloads the selected software during the installation process.  Only the software you select will be installed.  You can return and install additional software at any time.',
		helpDecideInstallNowTitle3: 'Recommended for',
		helpDecideInstallNowDesc3: 'Best option for installing Autodesk products directly on this computer.',
		helpDecideInstallNowActionBtn: 'Use Install Now',
		helpDecideInstallNowAdditionalInfo: 'Additional Information',
		
		helpDecideDownloadNowHeader: 'Download Now',
		helpDecideDownloadNowTitle1: 'Benefits',
		helpDecideDownloadNowDesc1: 'Delivers a complete standalone installation package with up to 50% compression and automatic download resumption after connection interruptions.',
		helpDecideDownloadNowTitle2: 'Whats Happens',
		helpDecideDownloadNowDesc2: 'A small download manager is first installed and enables an optimized download of the complete software installation package.  Once the installation package has downloaded you can begin the software installation on this or other computers without further connection to the internet.',
		helpDecideDownloadNowTitle3: 'Recommended for',
		helpDecideDownloadNowDesc3: 'Best option for installing Autodesk products on a different computer, or at a different time.',
		helpDecideDownloadNowActionBtn: 'Use Download Now',
		helpDecideDownloadNowAdditionalInfo: 'Additional Information',
		
		helpDecideBrowserDownloadHeader: 'Browser Download',
		helpDecideBrowserDownloadTitle1: 'Benefits',
		helpDecideBrowserDownloadDesc1: 'While it works without additional software or browser plug-ins, this is the least efficient delivery option, lacking both the superior compression and automatic download resumption abilities of the other download types.',
		helpDecideBrowserDownloadTitle2: 'Whats Happens',
		helpDecideBrowserDownloadDesc2: 'Uses the built-in file save mechanism of your web browser to deliver a complete standalone installation package. Once the installation package has downloaded you can begin the software installation on this or other computers without further connection to the internet.',
		helpDecideBrowserDownloadTitle3: 'Recommended for',
		helpDecideBrowserDownloadDesc3: 'We recommend this method only if you cannot install the Autodesk Download Manager.',
		helpDecideBrowserDownloadActionBtn: 'Use Browser Download',
		helpDecideBrowserDownloadAdditionalInfo: 'Additional Information',

		splitbtnInstallNow: 'Install Now',
		splitbtnDownloadNow: 'Download Now',
		splitbtnBrowserDownload: 'Browser Download',
		splitbtnHelpDecide: 'Help me decide'	
		},
		'zh-CN':{
		installInstHeader:'安装说明',
		installStep1:'当显示“Save or Run File”对话框时，选择“Run”',
		installStep2:'请遵循安装向导中的步骤。',
		installStep3:'如果收到浏览器警告，则选择“Allow”(我们也建议关闭此警告，以便将来从 Autodesk 下载)。',
		installStep4:'Autodesk Download Manager 现在已准备就绪，将自动开始交付您的选择。',
		installFooter:'发生问题？<a href="http://www.autodesk.com/">手动启动下载</a>',
		installInstMessage: '此下载需要安装 Autodesk Download Manager 实用程序。请完成以下步骤以下载并运行该小实用程序以便继续进行。',
		installUpgmessage: '需要安装 Autodesk Download Manager 的新版本。请完成以下步骤以下载并运行该小更新程序以便继续进行。',
		installAdditionalInfo: '附加信息',
		installUpgHeader: '升级说明',

		helpDecideHeader: '帮助我决定下载类型',
		helpDecideInstallNowHeader: '立即安装',
		helpDecideInstallNowTitle1: '优点',
		helpDecideInstallNowDesc1: '这是在此计算机上快速启动和运行的最佳方法，下载和安装所需时间少于浏览器下载和后续安装所用时间的一半。它可在下载前提供产品选择、高度压缩以及在连接中断后自动恢复下载。',
		helpDecideInstallNowTitle2: '结果',
		helpDecideInstallNowDesc2: '安装程序立即启动并在安装过程中下载选定的软件。将仅安装您选择的软件。您可以随时返回并安装其他软件。',
		helpDecideInstallNowTitle3: '推荐用途',
		helpDecideInstallNowDesc3: '这是在此计算机上直接安装 Autodesk 产品的最佳选择。',
		helpDecideInstallNowActionBtn: '立即使用安装',
		helpDecideInstallNowAdditionalInfo: '附加信息',
		
		helpDecideDownloadNowHeader: '立即下载',
		helpDecideDownloadNowTitle1: '优点',
		helpDecideDownloadNowDesc1: '提供完整的独立安装包，压缩率高达 50%，而且在连接中断后可自动恢复下载。',
		helpDecideDownloadNowTitle2: '结果',
		helpDecideDownloadNowDesc2: '先安装一个小的下载管理器，它支持完整软件安装包的优化下载。一旦下载了安装包，就可以在此计算机或其他计算机上开始软件安装，无需继续连接到 Internet。',
		helpDecideDownloadNowTitle3: '推荐用途',
		helpDecideDownloadNowDesc3: '这是在不同计算机或在不同时间安装 Autodesk 产品的最佳选择。',
		helpDecideDownloadNowActionBtn: '立即使用下载',
		helpDecideDownloadNowAdditionalInfo: '附加信息',
		
		helpDecideBrowserDownloadHeader: '浏览器下载',
		helpDecideBrowserDownloadTitle1: '优点',
		helpDecideBrowserDownloadDesc1: '尽管在没有其他软件或浏览器插件的情况下也可以使用它，但这是最低效的交付选择，既缺少高效的压缩又不具备其他下载类型的自动恢复下载的能力。',
		helpDecideBrowserDownloadTitle2: '结果',
		helpDecideBrowserDownloadDesc2: '使用 Web 浏览器的内置文件保存机制来提供完整的独立安装包。一旦下载了安装包，就可以在此计算机或其他计算机上开始软件安装，无需继续连接到 Internet。',
		helpDecideBrowserDownloadTitle3: '推荐用途',
		helpDecideBrowserDownloadDesc3: '仅当您无法安装 Autodesk Download Manager 时才建议使用此方法。',
		helpDecideBrowserDownloadActionBtn: '使用浏览器下载',
		helpDecideBrowserDownloadAdditionalInfo: '附加信息',

		splitbtnInstallNow: '立即安装',
		splitbtnDownloadNow: '立即下载',
		splitbtnBrowserDownload: '浏览器下载',
		splitbtnHelpDecide: '帮助我做出决定'	
		},
		'zh-TW':{
		installInstHeader:'安裝指示',
		installStep1:'出現「Save or Run File」對話方塊時，請選擇「Run」',
		installStep2:'請遵循設置精靈中的步驟。',
		installStep3:'若您收到瀏覽器警告，請選擇「Allow」(也建議您未來從 Autodesk 進行下載時均將此警告關閉)。',
		installStep4:'Autodesk Download Manager 現在已準備好並將自動開始傳送您選取的項目。',
		installFooter:'無法自動下載嗎？<a href="http://www.autodesk.com/">手動開始下載</a>',
		installInstMessage: '此下載需要安裝 Autodesk Download Manager 公用程式。請完成以下步驟以下載並執行小型公用程式繼續作業。',
		installUpgmessage: '需要安裝新版的 Autodesk Download Manager。請完成以下步驟以下載並執行小型公用程式繼續作業。',
		installAdditionalInfo: '其他資訊',
		installUpgHeader: '升級指示',

		helpDecideHeader: '協助我判斷下載類型',
		helpDecideInstallNowHeader: '立即安裝',
		helpDecideInstallNowTitle1: '優勢',
		helpDecideInstallNowDesc1: '在此電腦上快速啟動和執行的最佳方式，只需瀏覽器下載和後續安裝不到一半的時間。讓您可在下載前先進行產品選取、將下載檔案高度壓縮，並能在連線中斷後快速地繼續自動下載。',
		helpDecideInstallNowTitle2: '發生的狀況',
		helpDecideInstallNowDesc2: '安裝程式會立即開始安裝，在安裝期間並下載選取的軟體。系統僅會安裝您選取的軟體。您可以隨時返回並安裝其他軟體。',
		helpDecideInstallNowTitle3: '建議用於',
		helpDecideInstallNowDesc3: '直接在此部電腦上安裝 Autodesk 產品的最佳選項。',
		helpDecideInstallNowActionBtn: '使用「立即安裝」',
		helpDecideInstallNowAdditionalInfo: '其他資訊',
		
		helpDecideDownloadNowHeader: '立即下載',
		helpDecideDownloadNowTitle1: '優勢',
		helpDecideDownloadNowDesc1: '使用高達 50% 的壓縮率提供完整的單機版安裝套件，並會在中斷連線後自動繼續下載。',
		helpDecideDownloadNowTitle2: '發生的狀況',
		helpDecideDownloadNowDesc2: '首先會安裝小型的下載管理員，並啟用該完整軟體安裝套件的最佳化下載。安裝套件下載完成後，您便不需再連接至網際網路，即可開始在此台或其他電腦上進行軟體安裝。',
		helpDecideDownloadNowTitle3: '建議用於',
		helpDecideDownloadNowDesc3: '最適合用於在不同電腦 (或不同時間) 安裝 Autodesk 產品。',
		helpDecideDownloadNowActionBtn: '使用「立即下載」',
		helpDecideDownloadNowAdditionalInfo: '其他資訊',
		
		helpDecideBrowserDownloadHeader: '瀏覽器下載',
		helpDecideBrowserDownloadTitle1: '優勢',
		helpDecideBrowserDownloadDesc1: '儘管不需要其他軟體或瀏覽器外掛程式就可執行，但是因為缺乏其他下載類型所具備的優異壓縮功能和自動繼續下載能力，因此這是最沒有效率的提供選項。',
		helpDecideBrowserDownloadTitle2: '發生的狀況',
		helpDecideBrowserDownloadDesc2: '使用網路瀏覽器的內建儲存機制，提供完整的單機安裝套件。安裝套件下載完成後，您便不需再連接至網際網路，即可開始在此台或其他電腦上進行軟體安裝。',
		helpDecideBrowserDownloadTitle3: '建議用於',
		helpDecideBrowserDownloadDesc3: '僅建議您在無法安裝 Autodesk Download Manager 時才使用此方法。',
		helpDecideBrowserDownloadActionBtn: '使用「瀏覽器下載」',
		helpDecideBrowserDownloadAdditionalInfo: '其他資訊',

		splitbtnInstallNow: '立即安裝',
		splitbtnDownloadNow: '立即下載',
		splitbtnBrowserDownload: '瀏覽器下載',
		splitbtnHelpDecide: '協助我判斷'	
		},
		'cs-CZ':{
		installInstHeader:'Pokyny k instalaci',
		installStep1:'Jakmile se zobrazí dialog Save or Run File, klikněte na tlačítko Run.',
		installStep2:'Postupujte podle kroků v průvodci.',
		installStep3:'Pokud se zobrazí varování prohlížeče, klikněte na tlačítko Allow (doporučujeme také vypnout toto varování pro budoucí stahování souborů od společnosti Autodesk).',
		installStep4:'Nástroj Autodesk Download Manager začne automaticky stahovat vybranou položku.',
		installFooter:'Vyskytly se potíže? <a href="http://www.autodesk.com/">Spusťte stahování ručně.</a>',
		installInstMessage: 'Před stažením tohoto souboru je třeba nainstalovat nástroj Autodesk Download Manager. Než budete pokračovat, podle následujícího postupu tento malý nástroj stáhněte a spusťte.',
		installUpgmessage: 'Je třeba nainstalovat novou verzi nástroje Autodesk Download Manager. Než budete pokračovat, podle následujícího postupu tuto malou aktualizaci stáhněte a spusťte.',
		installAdditionalInfo: 'Další informace',
		installUpgHeader: 'Pokyny k upgradu',

		helpDecideHeader: 'Potřebuji poradit s výběrem metody stažení',
		helpDecideInstallNowHeader: 'Instalovat nyní',
		helpDecideInstallNowTitle1: 'Výhody',
		helpDecideInstallNowDesc1: 'Nejvhodnější způsob pro rychlé zahájení práce v tomto počítači. Stažení a instalace zabere méně než polovinu času oproti stažení prostřednictvím prohlížeče a následné instalaci. Nabízí výběr produktu před stažením, vysokou kompresi a automatické obnovení stahování v případě přerušení připojení.',
		helpDecideInstallNowTitle2: 'Co se stane',
		helpDecideInstallNowDesc2: 'Okamžitě se spustí instalační program, který během procesu instalace stáhne vybraný software. Nainstalován bude pouze vybraný software. Na tuto stránku se pak budete moci kdykoli vrátit a nainstalovat další software.',
		helpDecideInstallNowTitle3: 'Doporučeno pro',
		helpDecideInstallNowDesc3: 'Nejlepší možnost pro přímou instalaci produktů společnosti Autodesk do tohoto počítače.',
		helpDecideInstallNowActionBtn: 'Použít metodu Instalovat nyní',
		helpDecideInstallNowAdditionalInfo: 'Další informace',
		
		helpDecideDownloadNowHeader: 'Stáhnout nyní',
		helpDecideDownloadNowTitle1: 'Výhody',
		helpDecideDownloadNowDesc1: 'Stáhne celý balíček pro samostatnou instalaci až s 50% kompresí a s možností automatického obnovení stahování v případě přerušení připojení.',
		helpDecideDownloadNowTitle2: 'Co se stane',
		helpDecideDownloadNowDesc2: 'Nejprve bude nainstalován malý správce stahování, pomocí něhož můžete optimalizovat stažení úplného instalačního balíčku softwaru. Jakmile bude dokončeno stahování instalačního balíčku, můžete zahájit instalaci softwaru do tohoto počítače nebo jiných počítačů i bez připojení k internetu.',
		helpDecideDownloadNowTitle3: 'Doporučeno pro',
		helpDecideDownloadNowDesc3: 'Nejlepší možnost, pokud chcete produkty společnosti Autodesk instalovat později nebo do jiného počítače.',
		helpDecideDownloadNowActionBtn: 'Použít metodu Stáhnout nyní',
		helpDecideDownloadNowAdditionalInfo: 'Další informace',
		
		helpDecideBrowserDownloadHeader: 'Stažení prostřednictvím prohlížeče',
		helpDecideBrowserDownloadTitle1: 'Výhody',
		helpDecideBrowserDownloadDesc1: 'Tato metoda funguje bez dodatečného softwaru nebo modulů plug-in pro prohlížeč, ale je nejméně efektivní, protože na rozdíl od jiných metod stažení neumožňuje vysokou kompresi ani automatické obnovení stahování v případě přerušení připojení.',
		helpDecideBrowserDownloadTitle2: 'Co se stane',
		helpDecideBrowserDownloadDesc2: 'Pomocí integrovaného mechanismu webového prohlížeče pro ukládání souborů bude stažen úplný samostatný instalační balíček. Jakmile bude dokončeno stahování instalačního balíčku, můžete zahájit instalaci softwaru do tohoto počítače nebo jiných počítačů i bez připojení k internetu.',
		helpDecideBrowserDownloadTitle3: 'Doporučeno pro',
		helpDecideBrowserDownloadDesc3: 'Tuto metodu doporučujeme pouze v případě, že nemůžete nainstalovat nástroj Autodesk Download Manager.',
		helpDecideBrowserDownloadActionBtn: 'Použít metodu Stažení prostřednictvím prohlížeče',
		helpDecideBrowserDownloadAdditionalInfo: 'Další informace',

		splitbtnInstallNow: 'Instalovat nyní',
		splitbtnDownloadNow: 'Stáhnout nyní',
		splitbtnBrowserDownload: 'Stažení prostřednictvím prohlížeče',
		splitbtnHelpDecide: 'Potřebuji poradit'	
		},
		'de-DE':{
		installInstHeader:'Installationsanweisungen',
		installStep1:'Wählen Sie Run, wenn das Dialogfeld Save or Run File angezeigt wird',
		installStep2:'Folgen Sie den Schritten im Installationsassistenten.',
		installStep3:'Wählen Sie Allow, wenn Sie eine Browser-Warnung erhalten (es wird empfohlen, diese Warnung für zukünftige Downloads von Autodesk zu deaktivieren).',
		installStep4:'Autodesk Download Manager ist jetzt bereit und beginnt automatisch mit dem Download Ihrer Auswahl.',
		installFooter:'Probleme? <a href="http://www.autodesk.com/">Download manuell starten</a>',
		installInstMessage: 'Für diesen Download muss das Dienstprogramm Autodesk Download Manager installiert werden. Schließen Sie die folgenden Schritte ab, um das kleine Dienstprogramm herunterzuladen, auszuführen und fortzufahren.',
		installUpgmessage: 'Es muss eine neue Version von Autodesk Download Manager installiert werden. Schließen Sie die folgenden Schritte ab, um das kleine Dienstprogramm herunterzuladen, auszuführen und fortzufahren.',
		installAdditionalInfo: 'Zusätzliche Informationen',
		installUpgHeader: 'Upgrade-Anweisungen',

		helpDecideHeader: 'Download-Typ bestimmen',
		helpDecideInstallNowHeader: 'Jetzt installieren',
		helpDecideInstallNowTitle1: 'Vorteile',
		helpDecideInstallNowDesc1: 'So sind Sie auf diesem Computer schnell startbereit und haben den Browser-Download und die folgende Installation in weniger als einer halben Stunde abgeschlossen. Bietet Produktauswahl vor dem Download, hohe Komprimierung und die automatische Wiederaufnahme des Herunterladevorgangs nach Verbindungsunterbrechungen.',
		helpDecideInstallNowTitle2: 'Vorgehensweise',
		helpDecideInstallNowDesc2: 'Das Installationsprogramm startet sofort und lädt die ausgewählte Software während der Installation herunter. Nur die ausgewählte Software wird installiert. Sie können jederzeit zum Installationsprogramm zurückkehren und zusätzliche Software installieren.',
		helpDecideInstallNowTitle3: 'Empfehlung',
		helpDecideInstallNowDesc3: 'Beste Option für die Installation von Autodesk-Produkten direkt auf diesem Computer.',
		helpDecideInstallNowActionBtn: 'Option Jetzt installieren verwenden',
		helpDecideInstallNowAdditionalInfo: 'Zusätzliche Informationen',
		
		helpDecideDownloadNowHeader: 'Jetzt herunterladen',
		helpDecideDownloadNowTitle1: 'Vorteile',
		helpDecideDownloadNowDesc1: 'Stellt ein vollständiges Paket für eine Einzelplatzinstallation mit bis zu 50 % Komprimierung und automatischer Wiederaufnahme des Herunterladevorgangs nach Verbindungsunterbrechungen bereit.',
		helpDecideDownloadNowTitle2: 'Vorgehensweise',
		helpDecideDownloadNowDesc2: 'Zuerst wird ein kleiner Download-Manager installiert, der das optimale Herunterladen des vollständigen Installationspakets für die Software ermöglicht. Nach dem Herunterladen des Installationspakets kann die Software-Installation auf diesem oder anderen Computern ohne weitere Internetverbindung gestartet werden.',
		helpDecideDownloadNowTitle3: 'Empfehlung',
		helpDecideDownloadNowDesc3: 'Beste Option für die Installation von Autodesk-Produkten auf anderen Computern oder für die zeitversetzte Installation.',
		helpDecideDownloadNowActionBtn: 'Option Jetzt herunterladen verwenden',
		helpDecideDownloadNowAdditionalInfo: 'Zusätzliche Informationen',
		
		helpDecideBrowserDownloadHeader: 'Browser-Download',
		helpDecideBrowserDownloadTitle1: 'Vorteile',
		helpDecideBrowserDownloadDesc1: 'Diese Option ist die am wenigsten effiziente, auch wenn für diese Vorgehensweise keine zusätzliche Software oder Browser-Plugins erforderlich sind. Hier sind weder überdurchschnittliche Komprimierung noch Funktionen zur automatischen Wiederaufnahme des Herunterladevorgangs verfügbar, die von anderen Download-Typen geboten werden.',
		helpDecideBrowserDownloadTitle2: 'Vorgehensweise',
		helpDecideBrowserDownloadDesc2: 'Verwendet den integrierten Speichermechanismus des Browsers, um ein vollständiges Paket für eine Einzelplatzinstallation bereitzustellen. Nach dem Herunterladen des Installationspakets können Sie ohne weitere Internetverbindung mit der Software-Installation auf diesem oder anderen Computern beginnen.',
		helpDecideBrowserDownloadTitle3: 'Empfehlung',
		helpDecideBrowserDownloadDesc3: 'Diese Vorgehensweise wird nur dann empfohlen, wenn Sie Autodesk Download Manager nicht installieren können.',
		helpDecideBrowserDownloadActionBtn: 'Browser-Download verwenden',
		helpDecideBrowserDownloadAdditionalInfo: 'Zusätzliche Informationen',

		splitbtnInstallNow: 'Jetzt installieren',
		splitbtnDownloadNow: 'Jetzt herunterladen',
		splitbtnBrowserDownload: 'Browser-Download',
		splitbtnHelpDecide: 'Entscheidungshilfe'	
		},
		'es-ES':{
		installInstHeader:'Instrucciones de instalación',
		installStep1:'Cuando aparezca el cuadro de diálogo "Save or Run File", seleccione "Run".',
		installStep2:'Siga los pasos del asistente de instalación.',
		installStep3:'Si aparece una advertencia del navegador, seleccione "Allow" (es recomendable que desactive esta advertencia para futuras descargas de Autodesk).',
		installStep4:'Autodesk Download Manager ya está listo y comenzará a descargar automáticamente su selección.',
		installFooter:'¿Tiene algún problema? <a href="http://www.autodesk.com/">Inicie manualmente la descarga</a>',
		installInstMessage: 'Para realizar esta descarga, es necesario instalar Autodesk Download Manager. Para continuar, siga los pasos indicados a continuación a fin de descargar y ejecutar esta pequeña utilidad.',
		installUpgmessage: 'Debe instalar una nueva versión de Autodesk Download Manager. Para continuar, siga los pasos indicados a continuación a fin de descargar y ejecutar esta pequeña actualización.',
		installAdditionalInfo: 'Información adicional',
		installUpgHeader: 'Instrucciones de actualización',

		helpDecideHeader: 'Obtener más información para decidir el tipo de descarga',
		helpDecideInstallNowHeader: 'Instalar ahora',
		helpDecideInstallNowTitle1: 'Ventajas',
		helpDecideInstallNowDesc1: 'La mejor forma de obtener e instalar las descargas rápidamente en este equipo, ya que se tarda menos de la mitad de tiempo en realizar este proceso que con la opción "Descargar mediante el navegador". Ofrece una selección de los productos antes de realizar la descarga, un alto nivel de compresión y una función de reanudación automática de las descargas tras interrumpirse la conexión.',
		helpDecideInstallNowTitle2: 'Descripción del proceso',
		helpDecideInstallNowDesc2: 'El programa de instalación se inicia al instante y descarga el software seleccionado durante el proceso de instalación. Solo se instalará el software seleccionado. Puede volver e instalar software adicional en cualquier momento.',
		helpDecideInstallNowTitle3: 'Recomendado para',
		helpDecideInstallNowDesc3: 'La mejor opción para instalar los productos de Autodesk directamente en este equipo.',
		helpDecideInstallNowActionBtn: 'Utilizar la opción "Instalar ahora"',
		helpDecideInstallNowAdditionalInfo: 'Información adicional',
		
		helpDecideDownloadNowHeader: 'Descargar ahora',
		helpDecideDownloadNowTitle1: 'Ventajas',
		helpDecideDownloadNowDesc1: 'Proporciona un paquete competo de instalación independiente con hasta un 50% de compresión y una función de reanudación automática de las descargas tras interrumpirse la conexión.',
		helpDecideDownloadNowTitle2: 'Descripción del proceso',
		helpDecideDownloadNowDesc2: 'Se instala primero una pequeña utilidad de administración de descargas, que permite una descarga optimizada del paquete completo de instalación del software. Una vez descargado el paquete completo, puede iniciar la instalación del software en este u otros equipos sin necesidad de conectarse de nuevo a Internet.',
		helpDecideDownloadNowTitle3: 'Recomendado para',
		helpDecideDownloadNowDesc3: 'La mejor opción para instalar los productos de Autodesk en un equipo diferente o en el momento que desee.',
		helpDecideDownloadNowActionBtn: 'Utilizar la opción "Descargar ahora"',
		helpDecideDownloadNowAdditionalInfo: 'Información adicional',
		
		helpDecideBrowserDownloadHeader: 'Descargar mediante el navegador',
		helpDecideBrowserDownloadTitle1: 'Ventajas',
		helpDecideBrowserDownloadDesc1: 'Aunque no requiere software adicional ni módulos de extensión del navegador, se trata de la opción de descarga menos eficaz, ya que carece del alto nivel de compresión y de la función de reanudación automática que presentan los demás tipos de descargas.',
		helpDecideBrowserDownloadTitle2: 'Descripción del proceso',
		helpDecideBrowserDownloadDesc2: 'Utiliza el mecanismo integrado de almacenamiento de archivos del navegador web para proporcionar un paquete completo de instalación independiente. Una vez descargado el paquete, puede iniciar la instalación del software en este u otros equipos sin necesidad de conectarse de nuevo a Internet.',
		helpDecideBrowserDownloadTitle3: 'Recomendado para',
		helpDecideBrowserDownloadDesc3: 'Este método solo es recomendable si no puede instalar Autodesk Download Manager.',
		helpDecideBrowserDownloadActionBtn: 'Utilizar la opción "Descargar mediante el navegador"',
		helpDecideBrowserDownloadAdditionalInfo: 'Información adicional',

		splitbtnInstallNow: 'Instalar ahora',
		splitbtnDownloadNow: 'Descargar ahora',
		splitbtnBrowserDownload: 'Descargar mediante el navegador',
		splitbtnHelpDecide: 'Obtener más información para tomar una decisión'	
		},
		'fr-FR':{
		installInstHeader:'Instructions d\'installation',
		installStep1:'Lorsque la boîte de dialogue "Save or Run File" s\'affiche, choisissez "Run".',
		installStep2:'Suivez la procédure de l\'assistant d\'installation.',
		installStep3:'Si vous recevez un avertissement de votre navigateur, choisissez l\'option "Allow" (nous vous recommandons également de désactiver ce message d\'avertissement pour vos futurs téléchargements Autodesk).',
		installStep4:'Le gestionnaire de téléchargement Autodesk est désormais prêt et téléchargera automatiquement votre sélection.',
		installFooter:'Vous rencontrez des problèmes? <a href="http://www.autodesk.com/">Démarrer manuellement le téléchargement</a>',
		installInstMessage: 'Ce téléchargement doit installer l\'utilitaire du gestionnaire de téléchargement Autodesk. Effectuez la procédure suivante pour télécharger et exécuter le petit utilitaire en vue de continuer.',
		installUpgmessage: 'Une nouvelle version du gestionnaire de téléchargement Autodesk doit être installée. Effectuez la procédure suivante pour télécharger et exécuter la petite mise à jour en vue de continuer.',
		installAdditionalInfo: 'Informations supplémentaires',
		installUpgHeader: 'Instructions de mise à niveau',

		helpDecideHeader: 'M\'aider à choisir un type de téléchargement',
		helpDecideInstallNowHeader: 'Installer maintenant',
		helpDecideInstallNowTitle1: 'Avantages',
		helpDecideInstallNowDesc1: 'Méthode la plus adaptée pour mettre en oeuvre rapidement une application sur cet ordinateur, avec un téléchargement et une installation plus de 2 fois plus rapides que de télécharger le navigateur, puis effectuer l\'installation. Permet de sélectionner un produit avant de procéder au téléchargement, à une compression élevée, puis à une reprise automatique du téléchargement à la suite d\'interruptions de connexion.',
		helpDecideInstallNowTitle2: 'Que se passe-t-il?',
		helpDecideInstallNowDesc2: 'Le programme d\'installation démarre immédiatement et télécharge le logiciel sélectionné lors du processus d\'installation.  Seul le logiciel sélectionné sera installé.  Vous pouvez revenir sur vos pas et installer d\'autres logiciels à tout moment.',
		helpDecideInstallNowTitle3: 'Recommandé pour',
		helpDecideInstallNowDesc3: 'Option la plus adaptée pour installer des produits Autodesk directement sur cet ordinateur.',
		helpDecideInstallNowActionBtn: 'Utiliser l\'option Installer maintenant',
		helpDecideInstallNowAdditionalInfo: 'Informations supplémentaires',
		
		helpDecideDownloadNowHeader: 'Télécharger maintenant',
		helpDecideDownloadNowTitle1: 'Avantages',
		helpDecideDownloadNowDesc1: 'Fournit un module d\'installation autonome complet incluant jusqu\'à 50% de compression et une reprise automatique du téléchargement à la suite d\'interruptions de connexion.',
		helpDecideDownloadNowTitle2: 'Que se passe-t-il?',
		helpDecideDownloadNowDesc2: 'Un petit gestionnaire de téléchargement est d\'abord installé et permet un téléchargement optimisé du module d\'installation du logiciel complet.  Une fois le module d\'installation téléchargé, vous pouvez procéder à l\'installation du logiciel sur cet ordinateur (ou sur un autre ordinateur) sans qu\'aucune connexion supplémentaire à Internet ne soit requise.',
		helpDecideDownloadNowTitle3: 'Recommandé pour',
		helpDecideDownloadNowDesc3: 'Option la plus adaptée pour installer des produits Autodesk sur un autre ordinateur, ou ultérieurement.',
		helpDecideDownloadNowActionBtn: 'Utiliser l\'option Télécharger maintenant',
		helpDecideDownloadNowAdditionalInfo: 'Informations supplémentaires',
		
		helpDecideBrowserDownloadHeader: 'Téléchargement du navigateur',
		helpDecideBrowserDownloadTitle1: 'Avantages',
		helpDecideBrowserDownloadDesc1: 'Bien que fonctionnant sans aucun plug-in de navigateur ou logiciel supplémentaire, il s\'agit de l\'option la moins efficace, car aucune compression supérieure ni reprise automatique du téléchargement ne sont proposées (disponibles toutes deux avec les autres types de téléchargement).',
		helpDecideBrowserDownloadTitle2: 'Que se passe-t-il?',
		helpDecideBrowserDownloadDesc2: 'Utilise le mécanisme d\'enregistrement de fichier intégré de votre navigateur Web pour fournir un module d\'installation autonome complet. Une fois votre module d\'installation téléchargé, vous pouvez procéder à l\'installation du logiciel sur cet ordinateur (ou sur un autre ordinateur) sans qu\'aucune connexion supplémentaire à Internet ne soit requise.',
		helpDecideBrowserDownloadTitle3: 'Recommandé pour',
		helpDecideBrowserDownloadDesc3: 'Cette méthode est recommandée uniquement si vous ne pouvez pas installer le gestionnaire de téléchargement Autodesk.',
		helpDecideBrowserDownloadActionBtn: 'Utiliser l\'option Téléchargement du navigateur',
		helpDecideBrowserDownloadAdditionalInfo: 'Informations supplémentaires',

		splitbtnInstallNow: 'Installer maintenant',
		splitbtnDownloadNow: 'Télécharger maintenant',
		splitbtnBrowserDownload: 'Téléchargement du navigateur',
		splitbtnHelpDecide: 'M\'aider à effectuer ma sélection'	
		},
		'hu-HU':{
		installInstHeader:'Telepítési utasítások',
		installStep1:'Amikor megjelenik a Save or Run File párbeszédpanel, válassza a Run lehetőséget',
		installStep2:'Kövesse a telepítővarázsló lépéseit.',
		installStep3:'Ha a böngésző egy figyelmeztetést jelenít meg, válassza az Allow lehetőséget (javasoljuk, hogy kapcsolja ki ezt a figyelmeztetést az Autodesk későbbi letöltéseihez).',
		installStep4:'Az Autodesk Download Manager készen áll, és automatikusan elkezdi végrehajtani a kiválasztott műveleteket. ',
		installFooter:'Problémái vannak? <a href="http://www.autodesk.com/">A letöltés elindítása kézzel</a>',
		installInstMessage: 'A letöltéshez telepítenie kell az Autodesk Download Manager segédprogramot. A folytatáshoz hajtsa végre a következő lépéseket a kis segédprogram letöltéséhez és futtatásához.',
		installUpgmessage: 'Telepíteni kell az Autodesk Download Manager új verzióját. A folytatáshoz hajtsa végre a következő lépéseket a kis frissítés letöltéséhez és futtatásához.',
		installAdditionalInfo: 'További információk',
		installUpgHeader: 'Frissítési utasítások',

		helpDecideHeader: 'Segítség a letöltési típus kiválasztásához',
		helpDecideInstallNowHeader: 'Telepítés most',
		helpDecideInstallNowTitle1: 'Előnyök',
		helpDecideInstallNowDesc1: 'Ez a legjobb módszer a termék gyors telepítésére és futtatására a számítógépen, mivel a böngészővel végzett letöltéshez és az azt követő telepítéshez szükségesnél kevesebb, mint feleannyi időt igényel. A letöltés előtt kiválaszthatja a terméket, erős tömörítést alkalmazhat, és a kapcsolat megszakadása esetén a letöltés automatikusan folytatódik a helyreállás után.',
		helpDecideInstallNowTitle2: 'Mi történik',
		helpDecideInstallNowDesc2: 'A telepítő azonnal elindul, és letölti a kiválasztott szoftvert a telepítési folyamat során. Csak a kiválasztott szoftverek lesznek telepítve. Bármikor visszatérhet, és telepíthet további szoftvereket.',
		helpDecideInstallNowTitle3: 'A következő esetben ajánlott',
		helpDecideInstallNowDesc3: 'A legjobb lehetőség abban az esetben, ha közvetlenül erre a számítógépre telepíti az Autodesk termékeket.',
		helpDecideInstallNowActionBtn: 'A Telepítés most módszer használata',
		helpDecideInstallNowAdditionalInfo: 'További információk',
		
		helpDecideDownloadNowHeader: 'Letöltés most',
		helpDecideDownloadNowTitle1: 'Előnyök',
		helpDecideDownloadNowDesc1: 'Egy teljes önálló telepítőcsomagot biztosít, és akár 50%-os tömörítési arányt biztosít. A kapcsolat megszakadása esetén a letöltés automatikusan folytatódik a helyreállás után.',
		helpDecideDownloadNowTitle2: 'Mi történik',
		helpDecideDownloadNowDesc2: 'Először egy kis letöltéskezelő telepítése történik meg, amely lehetővé teszi a teljes szoftvertelepítő csomag optimalizált letöltését. Ha a telepítőcsomag letöltése kész, megkezdheti a szoftver telepítését erre a számítógépre vagy akár más számítógépekre is az internet használata nélkül.',
		helpDecideDownloadNowTitle3: 'A következő esetben ajánlott',
		helpDecideDownloadNowDesc3: 'A legjobb lehetőség az Autodesk termékek különböző számítógépekre, illetve különböző időpontokban végzett telepítésére.',
		helpDecideDownloadNowActionBtn: 'A Letöltés most módszer használata',
		helpDecideDownloadNowAdditionalInfo: 'További információk',
		
		helpDecideBrowserDownloadHeader: 'Letöltés a böngészőből',
		helpDecideBrowserDownloadTitle1: 'Előnyök',
		helpDecideBrowserDownloadDesc1: 'Ez a módszer további szoftverek vagy böngésző beépülő modulok nélkül működik, azonban ez a legkevésbé hatékony beszerzési lehetőség, amely nem kínál erős tömörítést, valamint nem képes a letöltések automatikus folytatására.',
		helpDecideBrowserDownloadTitle2: 'Mi történik',
		helpDecideBrowserDownloadDesc2: 'A böngésző beépített fájlmentési mechanizmusát használja a teljes önálló telepítőcsomag letöltéséhez. Ha a telepítőcsomag letöltése kész, megkezdheti a szoftver telepítését erre a számítógépre vagy akár más számítógépekre is az internet használata nélkül.',
		helpDecideBrowserDownloadTitle3: 'A következő esetben ajánlott',
		helpDecideBrowserDownloadDesc3: 'Csak akkor javasoljuk ezt a módszert, ha nem tudja telepíteni az Autodesk Download Manager segédprogramot.',
		helpDecideBrowserDownloadActionBtn: 'A Letöltés a böngészőből módszer használata',
		helpDecideBrowserDownloadAdditionalInfo: 'További információk',

		splitbtnInstallNow: 'Telepítés most',
		splitbtnDownloadNow: 'Letöltés most',
		splitbtnBrowserDownload: 'Letöltés a böngészőből',
		splitbtnHelpDecide: 'Segítség a kiválasztáshoz'	
		},
		'it-IT':{
		installInstHeader:'Istruzioni per l\'installazione',
		installStep1:'Quando viene visualizzata la finestra "Save or Run File", scegliere "Run"',
		installStep2:'Seguire i passaggi indicati nell\'installazione guidata.',
		installStep3:'Se si riceve un avviso del browser, scegliere "Allow" (si consiglia inoltre di disattivare questo avviso per i futuri download da Autodesk).',
		installStep4:'Autodesk Download Manager è pronto e inizierà automaticamente a scaricare gli elementi selezionati.',
		installFooter:'Se si verificano problemi, <a href="http://www.autodesk.com/">avviare manualmente il download</a>',
		installInstMessage: 'Per questo download è necessario installare l\'utilità Autodesk Download Manager. Completare questi passaggi per scaricare ed eseguire la piccola utilità per procedere.',
		installUpgmessage: 'È necessario installare una nuova versione di Autodesk Download Manager. Completare i seguenti passaggi per scaricare ed eseguire il piccolo aggiornamento per procedere.',
		installAdditionalInfo: 'Ulteriori informazioni',
		installUpgHeader: 'Istruzioni per l\'aggiornamento',

		helpDecideHeader: 'Aiutami a decidere un tipo di download',
		helpDecideInstallNowHeader: 'Installa ora',
		helpDecideInstallNowTitle1: 'Vantaggi',
		helpDecideInstallNowDesc1: 'Il modo migliore per essere rapidamente operativi su questo computer, con download e installazione in meno di metà del tempo richiesto dall\'opzione Download tramite browser e successiva installazione. Offre una selezione di prodotti prima del download, un\'elevata compressione e la ripresa automatica del download dopo le interruzioni della connessione.',
		helpDecideInstallNowTitle2: 'Cosa accade',
		helpDecideInstallNowDesc2: 'Il programma di installazione viene avviato immediatamente e scarica il software selezionato durante il processo di installazione. Viene installato solo il software selezionato.  È possibile tornare indietro e installare altri software in qualsiasi momento.',
		helpDecideInstallNowTitle3: 'Consigliato per',
		helpDecideInstallNowDesc3: 'La migliore opzione per l\'installazione dei prodotti Autodesk direttamente su questo computer.',
		helpDecideInstallNowActionBtn: 'Utilizza Installa ora',
		helpDecideInstallNowAdditionalInfo: 'Ulteriori informazioni',
		
		helpDecideDownloadNowHeader: 'Scarica ora',
		helpDecideDownloadNowTitle1: 'Vantaggi',
		helpDecideDownloadNowDesc1: 'Fornisce un pacchetto di installazione indipendente completo con una compressione fino al 50% e la ripresa automatica del download dopo le interruzioni della connessione.',
		helpDecideDownloadNowTitle2: 'Cosa accade',
		helpDecideDownloadNowDesc2: 'Viene innanzitutto installato un piccolo gestore di download, che consente un download ottimizzato del pacchetto di installazione software completo. Una volta scaricato il pacchetto di installazione, è possibile iniziare l\'installazione del software su questo o altri computer senza ulteriore connessione a Internet.',
		helpDecideDownloadNowTitle3: 'Consigliato per',
		helpDecideDownloadNowDesc3: 'La scelta ideale per l\'installazione dei prodotti Autodesk su altri computer o in momenti diversi.',
		helpDecideDownloadNowActionBtn: 'Utilizza Scarica ora',
		helpDecideDownloadNowAdditionalInfo: 'Ulteriori informazioni',
		
		helpDecideBrowserDownloadHeader: 'Download tramite browser',
		helpDecideBrowserDownloadTitle1: 'Vantaggi',
		helpDecideBrowserDownloadDesc1: 'Anche se funziona senza software aggiuntivi o plug-in del browser, è l\'opzione meno efficiente perché manca dell\'elevato livello di compressione e della capacità di ripresa automatica del download fornite dagli atri tipi di download.',
		helpDecideBrowserDownloadTitle2: 'Cosa accade',
		helpDecideBrowserDownloadDesc2: 'Utilizza il meccanismo di salvataggio dei file integrato del browser Web per scaricare un pacchetto di installazione indipendente completo. Una volta scaricato il pacchetto di installazione, è possibile iniziare l\'installazione del software su questo o altri computer senza ulteriore connessione a Internet.',
		helpDecideBrowserDownloadTitle3: 'Consigliato per',
		helpDecideBrowserDownloadDesc3: 'Si consiglia questo metodo se non è possibile installare Autodesk Download Manager.',
		helpDecideBrowserDownloadActionBtn: 'Utilizza Download tramite browser',
		helpDecideBrowserDownloadAdditionalInfo: 'Ulteriori informazioni',

		splitbtnInstallNow: 'Installa ora',
		splitbtnDownloadNow: 'Scarica ora',
		splitbtnBrowserDownload: 'Download tramite browser',
		splitbtnHelpDecide: 'Informazioni'	
		},
		'ja-JP':{
		installInstHeader:'インストール方法',
		installStep1:'"Save or Run File" ダイアログ ボックスが表示されたら、"Run" を選択します。',
		installStep2:'セットアップ ウィザードの以降の指示に従って操作してください。',
		installStep3:'ブラウザに警告が表示された場合、"Allow" を選択してください(これ以降のオートデスクからのダウンロードのために、この警告をオフにすることをお勧めします)。',
		installStep4:'Autodesk Download Manager の準備ができました。選択した項目のダウンロードは自動的に開始されます。',
		installFooter:'何か問題がある場合は、<a href="http://www.autodesk.com/">ダウンロードを手動で開始</a>を参照してください。',
		installInstMessage: 'このダウンロードには Autodesk Download Manager ユーティリティが必要です。次に示す手順により、このユーティリティをダウンロードして実行してください。',
		installUpgmessage: '新しいバージョンの Autodesk Download Manager をインストールしてください。次に示す手順により、このユーティリティをダウンロードして実行してください。',
		installAdditionalInfo: '追加情報',
		installUpgHeader: '更新方法',

		helpDecideHeader: 'ダウンロードの種類を決定するには',
		helpDecideInstallNowHeader: '今すぐインストール',
		helpDecideInstallNowTitle1: 'メリット',
		helpDecideInstallNowDesc1: 'お使いのコンピュータに迅速にインストールして使用したい場合に最適な方法です。「ブラウザでダウンロード」の方法で行う場合の半分以下の時間でダウンロードとインストールを完了することができます。ダウンロードを実行する前に、製品の選択、圧縮転送、途中で接続が切れた場合の自動再開などのオプションを選択できます。',
		helpDecideInstallNowTitle2: '実行される内容',
		helpDecideInstallNowDesc2: 'インストーラが直ちに起動され、選択したソフトウェアのダウンロードはインストール プロセス中に行われます。選択したソフトウェアのみがインストールされます。追加のソフトウェアのインストールはいつでも行えます。',
		helpDecideInstallNowTitle3: 'このような場合にお勧めします',
		helpDecideInstallNowDesc3: 'オートデスク製品をこのコンピュータにインストールする場合に最適な方法です。',
		helpDecideInstallNowActionBtn: '「今すぐインストール」を使用',
		helpDecideInstallNowAdditionalInfo: '追加情報',
		
		helpDecideDownloadNowHeader: '今すぐダウンロード',
		helpDecideDownloadNowTitle1: 'メリット',
		helpDecideDownloadNowDesc1: 'スタンドアロン インストレーション パッケージを 50% の圧縮率でダウンロードできます。途中で接続が切れた場合は自動的にダウンロードを再開します。',
		helpDecideDownloadNowTitle2: '実行される内容',
		helpDecideDownloadNowDesc2: '最初に Autodesk Download Manager というユーティリティがインストールされ、完全なソフトウェア インストレーション パッケージを最適にダウンロードできるようになります。インストレーション パッケージのダウンロード後は、このコンピュータ、あるいは別のコンピュータにおいてソフトウェアのインストールを行えます。この時点でのインターネット接続は必要ありません。',
		helpDecideDownloadNowTitle3: 'このような場合にお勧めします',
		helpDecideDownloadNowDesc3: 'この方法は、オートデスク製品を異なるコンピュータにインストールする場合や、後日インストールする場合にお勧めします。',
		helpDecideDownloadNowActionBtn: '「今すぐダウンロード」を使用',
		helpDecideDownloadNowAdditionalInfo: '追加情報',
		
		helpDecideBrowserDownloadHeader: 'ブラウザでダウンロード',
		helpDecideBrowserDownloadTitle1: 'メリット',
		helpDecideBrowserDownloadDesc1: '追加のユーティリティやプラグインをインストールすることなくダウンロードを行えます。ただし、他のダウンロード方法のような圧縮転送や途中で接続が切れた場合の自動再開などのオプションはありません。',
		helpDecideBrowserDownloadTitle2: '実行される内容',
		helpDecideBrowserDownloadDesc2: 'お使いのブラウザで標準のファイル保存機能を使用して、完全なスタンドアロン インストレーション パッケージをダウンロードできます。ダウンロード後は、このコンピュータ、あるいは別のコンピュータにおいてソフトウェアのインストールを行えます。この時点でのインターネット接続は必要ありません。',
		helpDecideBrowserDownloadTitle3: 'このような場合にお勧めします',
		helpDecideBrowserDownloadDesc3: 'この方法は、Autodesk Download Manager をインストールできない場合にお勧めします。',
		helpDecideBrowserDownloadActionBtn: '「ブラウザでダウンロード」を使用',
		helpDecideBrowserDownloadAdditionalInfo: '追加情報',

		splitbtnInstallNow: '今すぐインストール',
		splitbtnDownloadNow: '今すぐダウンロード',
		splitbtnBrowserDownload: 'ブラウザでダウンロード',
		splitbtnHelpDecide: '決定するには'	
		},
		'ko-KR':{
		installInstHeader:'설치 지침',
		installStep1:'"Save or Run File" 대화상자가 표시되면 "Run"을 선택합니다.',
		installStep2:'설치 마법사의 단계를 따릅니다.',
		installStep3:'브라우저 경고가 표시되면 "Allow"를 선택합니다. 또한 이후에도 Autodesk에서 다운로드할 수 있도록 이 경고를 끄는 것이 좋습니다.',
		installStep4:'이제 Autodesk Download Manager가 준비되었으며 선택 항목이 자동으로 제공됩니다.',
		installFooter:'문제가 발생하면 <a href="http://www.autodesk.com/">다운로드를 수동으로 시작</a>하십시오.',
		installInstMessage: '이 항목을 다운로드하려면 Autodesk Download Manager 유틸리티를 설치해야 합니다. 계속하려면 다음 단계를 완료하여 소형 유틸리티를 다운로드 및 실행하십시오.',
		installUpgmessage: '새 Autodesk Download Manager 버전을 설치해야 합니다. 계속하려면 다음 단계를 완료하여 소형 업데이트를 다운로드 및 실행하십시오.',
		installAdditionalInfo: '추가 정보',
		installUpgHeader: '업그레이드 지침',

		helpDecideHeader: '다운로드 유형 결정 도움말',
		helpDecideInstallNowHeader: '지금 설치',
		helpDecideInstallNowTitle1: '장점',
		helpDecideInstallNowDesc1: '이 컴퓨터에서 다운로드를 빠르게 설치하고 실행하기 위한 가장 효율적인 방법으로, 다운로드 및 설치 시간이 브라우저 다운로드 및 후속 설치 시간의 절반에 불과합니다. 다운로드 전에 제품을 선택할 수 있고, 높은 비율로 압축된 파일이 제공되며, 연결이 끊어진 후 다운로드가 자동으로 다시 시작됩니다.',
		helpDecideInstallNowTitle2: '수행 작업',
		helpDecideInstallNowDesc2: '설치 프로그램이 즉시 시작되어 설치 프로세스 중에 선택한 소프트웨어를 다운로드합니다. 선택한 소프트웨어만 설치됩니다. 언제든지 선택 화면으로 돌아와서 추가 소프트웨어를 설치할 수 있습니다.',
		helpDecideInstallNowTitle3: '권장 대상',
		helpDecideInstallNowDesc3: '이 컴퓨터에 Autodesk 제품을 직접 설치하려는 경우 가장 적절한 옵션입니다.',
		helpDecideInstallNowActionBtn: '지금 설치 사용',
		helpDecideInstallNowAdditionalInfo: '추가 정보',
		
		helpDecideDownloadNowHeader: '지금 다운로드',
		helpDecideDownloadNowTitle1: '장점',
		helpDecideDownloadNowDesc1: '완전한 독립 실행형 설치 패키지(압축률 최대 50%)가 제공되며, 연결이 끊어진 후 다운로드가 자동으로 다시 시작됩니다.',
		helpDecideDownloadNowTitle2: '수행 작업',
		helpDecideDownloadNowDesc2: '전체 소프트웨어 설치 패키지를 최적화된 상태로 다운로드할 수 있도록 소형 Download Manager가 먼저 설치됩니다. 설치 패키지가 다운로드되고 나면 더 이상 인터넷에 연결하지 않고도 이 컴퓨터 또는 다른 컴퓨터에서 소프트웨어 설치를 시작할 수 있습니다.',
		helpDecideDownloadNowTitle3: '권장 대상',
		helpDecideDownloadNowDesc3: '다른 컴퓨터에 또는 다른 이름으로 Autodesk 제품을 설치하려는 경우 가장 적절한 옵션입니다.',
		helpDecideDownloadNowActionBtn: '지금 다운로드 사용',
		helpDecideDownloadNowAdditionalInfo: '추가 정보',
		
		helpDecideBrowserDownloadHeader: '브라우저 다운로드',
		helpDecideBrowserDownloadTitle1: '장점',
		helpDecideBrowserDownloadDesc1: '이 방식은 추가 소프트웨어 또는 브라우저 플러그인 없이도 작동하기는 하지만 다른 다운로드 유형에서 제공되는 뛰어난 압축 및 자동 다운로드 다시 시작 기능이 모두 제공되지 않아 효율성이 가장 떨어지는 제공 옵션입니다.',
		helpDecideBrowserDownloadTitle2: '수행 작업',
		helpDecideBrowserDownloadDesc2: '웹 브라우저의 내장 파일 저장 메커니즘을 사용하여 완전한 독립 실행형 설치 패키지를 제공합니다. 설치 패키지가 다운로드되고 나면 더 이상 인터넷에 연결하지 않고도 이 컴퓨터 또는 다른 컴퓨터에서 소프트웨어 설치를 시작할 수 있습니다.',
		helpDecideBrowserDownloadTitle3: '권장 대상',
		helpDecideBrowserDownloadDesc3: '이 방법은 Autodesk Download Manager를 설치할 수 없는 경우에만 사용하는 것이 좋습니다.',
		helpDecideBrowserDownloadActionBtn: '브라우저 다운로드 사용',
		helpDecideBrowserDownloadAdditionalInfo: '추가 정보',

		splitbtnInstallNow: '지금 설치',
		splitbtnDownloadNow: '지금 다운로드',
		splitbtnBrowserDownload: '브라우저 다운로드',
		splitbtnHelpDecide: '결정 도움말'	
		},
		'nl-NL':{
		installInstHeader:'Installatie-instructies',
		installStep1:'Kies in het dialoogvenster "Save or Run File" de optie "Run"',
		installStep2:'Volg de stappen in de wizard Instellingen op.',
		installStep3:'Als u een browserwaarschuwing krijgt, kiest u "Allow" (we raden u aan deze waarschuwing uit te schakelen voor toekomstige downloads van Autodesk).',
		installStep4:'Autodesk Download Manager is nu klaar en zal automatisch uw selectie uitvoeren.',
		installFooter:'Ervaart u problemen? <a href="http://www.autodesk.com/">Start de download handmatig</a>',
		installInstMessage: 'Deze download moet het hulpprogramma Autodesk Download Manager installeren. Voltooi de volgende stappen om te downloaden en start het kleine hulpprogrammaatje om door te gaan.',
		installUpgmessage: 'Er moet een nieuwe versie van Autodesk Download Manager worden geïnstalleerd. Voltooi de volgende stappen om de kleine update te downloaden en uit te voeren, alvorens door te gaan.',
		installAdditionalInfo: 'Extra informatie',
		installUpgHeader: 'Upgrade-instructies',

		helpDecideHeader: 'Help me bij het kiezen van een downloadtype',
		helpDecideInstallNowHeader: 'Nu installeren',
		helpDecideInstallNowTitle1: 'Voordelen',
		helpDecideInstallNowDesc1: 'De beste manier om snel op deze computer aan de slag te gaan, omdat downloaden en installeren twee keer zo snel gaat als downloaden via een browser en vervolgens installeren. Voordelen zijn de productaanbiedingen voordat het downloaden van start gaat, hoge compressie en het automatisch hervatten van de download als er fouten optreden vanwege een wegvallende verbinding.',
		helpDecideInstallNowTitle2: 'Wat er gebeurt',
		helpDecideInstallNowDesc2: 'Het installatieprogramma start de installatieprocedure meteen met het downloaden van de geselecteerde software. Alleen de software die u hebt geselecteerd, wordt geïnstalleerd. U kunt op elk gewenst moment teruggaan om extra software te installeren.',
		helpDecideInstallNowTitle3: 'Aanbevolen voor',
		helpDecideInstallNowDesc3: 'Beste optie voor het rechtstreeks installeren van Autodesk-producten op deze computer.',
		helpDecideInstallNowActionBtn: 'Nu installeren gebruiken',
		helpDecideInstallNowAdditionalInfo: 'Extra informatie',
		
		helpDecideDownloadNowHeader: 'Nu downloaden',
		helpDecideDownloadNowTitle1: 'Voordelen',
		helpDecideDownloadNowDesc1: 'Biedt een compleet, zelfstandig draaiend installatiepakket met compressie tot 50% en het automatisch hervatten van de download na fouten door het wegvallen van de verbinding.',
		helpDecideDownloadNowTitle2: 'Wat er gebeurt',
		helpDecideDownloadNowDesc2: 'Eerst wordt een kleine downloadmanager geïnstalleerd, die zorgt voor een geoptimaliseerde download van het complete installatiepakket. Na het downloaden van het installatiepakket kunt u de software installeren op deze of een andere computer zonder internetverbinding.',
		helpDecideDownloadNowTitle3: 'Aanbevolen voor',
		helpDecideDownloadNowDesc3: 'Beste optie voor het installeren van Autodesk-producten op een andere computer, of op een andere tijd.',
		helpDecideDownloadNowActionBtn: 'Nu downloaden gebruiken',
		helpDecideDownloadNowAdditionalInfo: 'Extra informatie',
		
		helpDecideBrowserDownloadHeader: 'Downloaden via browser',
		helpDecideBrowserDownloadTitle1: 'Voordelen',
		helpDecideBrowserDownloadDesc1: 'Deze methode werkt zonder extra software of plugins voor de browser, en is daarom de minst efficiënte manier om de software op te halen, omdat er geen superieure compressie wordt gebruikt en er geen mogelijkheden zijn om de download automatisch te hervatten bij fouten, zoals bij de andere downloadtypen mogelijk is.',
		helpDecideBrowserDownloadTitle2: 'Wat er gebeurt',
		helpDecideBrowserDownloadDesc2: 'Gebruikt een ingebouwd bestandsopslagmechanisme voor uw webbrowser voor een compleet, zelfstandig draaiend installatiepakket. Als het installatiepakket is gedownload, kunt u de software installeren op deze of een andere computer zonder internetverbinding.',
		helpDecideBrowserDownloadTitle3: 'Aanbevolen voor',
		helpDecideBrowserDownloadDesc3: 'We raden deze methode alleen aan als u de Autodesk Download Manager niet kunt installeren.',
		helpDecideBrowserDownloadActionBtn: 'Downloaden via browser gebruiken',
		helpDecideBrowserDownloadAdditionalInfo: 'Extra informatie',

		splitbtnInstallNow: 'Nu installeren',
		splitbtnDownloadNow: 'Nu downloaden',
		splitbtnBrowserDownload: 'Downloaden via browser',
		splitbtnHelpDecide: 'Help me kiezen'	
		},
		'pl-PL':{
		installInstHeader:'Instrukcje instalacji',
		installStep1:'Po wyświetleniu okna dialogowego Save or Run File wybierz opcję Run',
		installStep2:'Wykonaj kroki przedstawione w kreatorze konfiguracji.',
		installStep3:'W przypadku wyświetlenia ostrzeżenia przeglądarki wybierz opcję Allow (zalecamy również wyłączenie tego ostrzeżenia dla przyszłych operacji pobierania materiałów Autodesk).',
		installStep4:'Program Autodesk Download Manager jest teraz gotowy i automatycznie dostarczy wybrane materiały.',
		installFooter:'Napotykasz problemy? <a href="http://www.autodesk.com/">Uruchom pobieranie ręcznie</a>',
		installInstMessage: 'W celu wykonania pobrania konieczne jest zainstalowanie narzędzia Autodesk Download Manager. Wykonaj następujące kroki, aby pobrać i uruchomić to niewielkie narzędzie i kontynuować.',
		installUpgmessage: 'Należy zainstalować nową wersję programu Autodesk Download Manager. Wykonaj następujące kroki, aby pobrać oraz uruchomić tę niewielką aktualizację i kontynuować.',
		installAdditionalInfo: 'Informacje dodatkowe',
		installUpgHeader: 'Instrukcje aktualizacji',

		helpDecideHeader: 'Pomóż mi podjąć decyzję dotyczącą typu pobierania',
		helpDecideInstallNowHeader: 'Install Now',
		helpDecideInstallNowTitle1: 'Korzyści',
		helpDecideInstallNowDesc1: 'Najlepsza metoda szybkiego pobrania i uruchomienia na tym komputerze, zapewniająca czas pobierania i instalacji krótszy niż połowa czasu pobierania za pomocą przeglądarki i późniejszej instalacji. Oferuje wybór produktu przed pobraniem, wysoki stopień kompresji oraz automatyczne wznawianie pobierania po przerwaniu połączenia.',
		helpDecideInstallNowTitle2: 'Co się dzieje',
		helpDecideInstallNowDesc2: 'Instalator uruchamia się natychmiast i pobiera w trakcie procesu instalacji wybrane oprogramowanie. Zainstalowane zostanie tylko wybrane oprogramowanie. W dowolnym momencie można powrócić do dodatkowego oprogramowania i zainstalować je.',
		helpDecideInstallNowTitle3: 'Zalecane dla',
		helpDecideInstallNowDesc3: 'Najlepsza opcja instalacji produktów Autodesk bezpośrednio na tym komputerze.',
		helpDecideInstallNowActionBtn: 'Użyj instalatora Install Now',
		helpDecideInstallNowAdditionalInfo: 'Informacje dodatkowe',
		
		helpDecideDownloadNowHeader: 'Pobierz teraz',
		helpDecideDownloadNowTitle1: 'Korzyści',
		helpDecideDownloadNowDesc1: 'Dostarcza kompletny autonomiczny pakiet instalacyjny o stopniu kompresji do 50% i automatycznie wznawia pobieranie po przerwaniu połączenia.',
		helpDecideDownloadNowTitle2: 'Co się dzieje',
		helpDecideDownloadNowDesc2: 'Mały menedżer pobierania jest instalowany najpierw i umożliwia optymalizację pobierania kompletnego pakietu instalacyjnego oprogramowania. Po pobraniu pakietu instalacyjnego można rozpocząć instalację na tym lub innych komputerach bez dalszego połączenia z Internetem.',
		helpDecideDownloadNowTitle3: 'Zalecane dla',
		helpDecideDownloadNowDesc3: 'Najlepsza opcja instalacji produktów Autodesk na innym komputerze lub w innym czasie.',
		helpDecideDownloadNowActionBtn: 'Użyj opcji Pobierz teraz',
		helpDecideDownloadNowAdditionalInfo: 'Informacje dodatkowe',
		
		helpDecideBrowserDownloadHeader: 'Pobierz za pomocą przeglądarki',
		helpDecideBrowserDownloadTitle1: 'Korzyści',
		helpDecideBrowserDownloadDesc1: 'Funkcja działa bez wykorzystania dodatkowego oprogramowania i wtyczek przeglądarki, jest jednak najmniej wydajną opcją dostarczania, pozbawioną wysokiego stopnia kompresji i możliwości automatycznego wznawiania pobierania, występujących w innych typach pobierania.',
		helpDecideBrowserDownloadTitle2: 'Co się dzieje',
		helpDecideBrowserDownloadDesc2: 'Wykorzystuje wbudowany mechanizm zapisywania pliku przeglądarki WWW w celu dostarczenia kompletnego autonomicznego pakietu instalacyjnego. Po pobraniu pakietu instalacyjnego można rozpocząć instalację na tym lub innych komputerach bez dalszego połączenia z Internetem.',
		helpDecideBrowserDownloadTitle3: 'Zalecane dla',
		helpDecideBrowserDownloadDesc3: 'Tę metodę zalecamy tylko w przypadku, gdy nie można pobrać programu Autodesk Download Manager.',
		helpDecideBrowserDownloadActionBtn: 'Użyj opcji Pobierz za pomocą przeglądarki',
		helpDecideBrowserDownloadAdditionalInfo: 'Informacje dodatkowe',

		splitbtnInstallNow: 'Install Now',
		splitbtnDownloadNow: 'Pobierz teraz',
		splitbtnBrowserDownload: 'Pobierz za pomocą przeglądarki',
		splitbtnHelpDecide: 'Pomóż mi podjąć decyzję'	
		},
		'pt-BR':{
		installInstHeader:'Instruções de instalação',
		installStep1:'Quando a caixa de diálogo "Save or Run File" for exibida, escolha "Run"',
		installStep2:'Siga os passos no assistente de configuração.',
		installStep3:'Caso receba um aviso em seu navegador, escolha "Allow" (também recomendamos que desative esse aviso para futuros downloads da Autodesk).',
		installStep4:'O Autodesk Download Manager já está pronto e começará a transferir automaticamente sua seleção.',
		installFooter:'Está com problemas? <a href="http://www.autodesk.com/">Inicie manualmente o download</a>',
		installInstMessage: 'Este download precisa da instalação do utilitário Autodesk Download Manager. Siga os seguintes passos para descarregar e executar o pequeno utilitário para prosseguir.',
		installUpgmessage: 'Uma nova versão do Autodesk Download Manager deve ser instalada. Siga os seguintes passos para descarregar e executar a pequena atualização para prosseguir.',
		installAdditionalInfo: 'Informações adicionais',
		installUpgHeader: 'Instruções de atualização',

		helpDecideHeader: 'Ajude-me a decidir um tipo de download',
		helpDecideInstallNowHeader: 'Instalar agora',
		helpDecideInstallNowTitle1: 'Benefícios',
		helpDecideInstallNowDesc1: 'A melhor maneira de instalar e executar programas rapidamente em seu computador, com download e instalação em menos da metade do tempo de um download em navegador seguido de instalação. Oferece a seleção de produtos antes do download, alta compressão e reinício automático do download após interrupções de conexão.',
		helpDecideInstallNowTitle2: 'O que acontece',
		helpDecideInstallNowDesc2: 'O instalador inicia imediatamente e descarrega o software selecionado durante o processo de instalação. Somente o software que você selecionou será instalado. Você pode voltar e instalar softwares adicionais a qualquer momento.',
		helpDecideInstallNowTitle3: 'Recomendado para',
		helpDecideInstallNowDesc3: 'A melhor opção para instalar produtos da Autodesk diretamente em seu computador.',
		helpDecideInstallNowActionBtn: 'Usar a opção Instalar agora',
		helpDecideInstallNowAdditionalInfo: 'Informações adicionais',
		
		helpDecideDownloadNowHeader: 'Fazer download agora',
		helpDecideDownloadNowTitle1: 'Benefícios',
		helpDecideDownloadNowDesc1: 'Transfere um pacote completo de instalação independente com até 50% de compressão e reinício automático de download após interrupções de conexão.',
		helpDecideDownloadNowTitle2: 'O que acontece',
		helpDecideDownloadNowDesc2: 'Primeiro é instalado um pequeno gerenciador de download que permite um download otimizado do pacote completo de instalação de software. Uma vez que o pacote de instalação for descarregado, é possível começar a instalação do software neste computador ou em outros computadores, sem necessidade de conexão à internet.',
		helpDecideDownloadNowTitle3: 'Recomendado para',
		helpDecideDownloadNowDesc3: 'A melhor opção para instalar produtos da Autodesk em diferentes computadores ou em momentos distintos.',
		helpDecideDownloadNowActionBtn: 'Usar a opção Fazer download agora',
		helpDecideDownloadNowAdditionalInfo: 'Informações adicionais',
		
		helpDecideBrowserDownloadHeader: 'Fazer download do navegador',
		helpDecideBrowserDownloadTitle1: 'Benefícios',
		helpDecideBrowserDownloadDesc1: 'Enquanto funciona sem plug-ins de navegador ou software adicional, essa é a opção de transferência menos eficiente, desprovida de recursos de compressão superiores e reinício de download automático de outros tipos de download.',
		helpDecideBrowserDownloadTitle2: 'O que acontece',
		helpDecideBrowserDownloadDesc2: 'Usa o mecanismo de salvamento de arquivos integrado de seu navegador da web para transferir um pacote completo de instalação independente. Uma vez que o pacote de instalação é descarregado, é possível começar a instalação do software neste computador ou em outros computadores, sem a necessidade de conexão à internet.',
		helpDecideBrowserDownloadTitle3: 'Recomendado para',
		helpDecideBrowserDownloadDesc3: 'Recomendamos este método somente se não for possível instalar o Autodesk Download Manager.',
		helpDecideBrowserDownloadActionBtn: 'Usar Fazer download do navegador',
		helpDecideBrowserDownloadAdditionalInfo: 'Informações adicionais',

		splitbtnInstallNow: 'Instalar agora',
		splitbtnDownloadNow: 'Fazer download agora',
		splitbtnBrowserDownload: 'Fazer download do navegador',
		splitbtnHelpDecide: 'Ajude-me a decidir'	
		},
		'ru-RU':{
		installInstHeader:'Инструкции по установке',
		installStep1:'В диалоговом окне  "Save or Run File" выберите "Run".',
		installStep2:'Выполните следующие действия в мастере настройки.',
		installStep3:'Если появится предупреждение браузера, выберите "Allow" (это предупреждение также рекомендуется выключать для последующих загрузок с сервера Autodesk).',
		installStep4:'Теперь Autodesk Download Manager готов к работе и автоматически начинает загрузку выбранных элементов.',
		installFooter:'Проблемы? <a href="http://www.autodesk.ru/">Запустите загрузку вручную</a>',
		installInstMessage: 'Для загрузки требуется установить утилиту Autodesk Download Manager. Выполните следующие действия, чтобы загрузить и запустить эту небольшую утилиту для продолжения загрузки.',
		installUpgmessage: 'Необходимо установить новую версию Autodesk Download Manager. Выполните следующие действия, чтобы загрузить и запустить это небольшое обновление для продолжения загрузки.',
		installAdditionalInfo: 'Дополнительные сведения',
		installUpgHeader: 'Инструкции по обновлению',

		helpDecideHeader: 'Помощь в выборе типа загрузки',
		helpDecideInstallNowHeader: 'Install Now',
		helpDecideInstallNowTitle1: 'Преимущества',
		helpDecideInstallNowDesc1: 'Лучший способ быстро настроить и запустить программу на компьютере: время загрузки и установки в два раза меньше, чем при загрузке с помощью браузера и последующей установке. Перед загрузкой предоставляется возможность выбрать продукт, обеспечивается высокая степень сжатия и автоматическое возобновление загрузки в случае разрыва соединения.',
		helpDecideInstallNowTitle2: 'Принцип работы',
		helpDecideInstallNowDesc2: 'Программа установки сразу запускается и в процессе установки загружает выбранное ПО. Устанавливается только выбранное ПО. В любое время можно вернуться и установить дополнительное ПО.',
		helpDecideInstallNowTitle3: 'Рекомендации',
		helpDecideInstallNowDesc3: 'Лучший способ загрузки продуктов Autodesk прямо на этот компьютер.',
		helpDecideInstallNowActionBtn: 'Использовать Install Now',
		helpDecideInstallNowAdditionalInfo: 'Дополнительные сведения',
		
		helpDecideDownloadNowHeader: 'Загрузить сейчас',
		helpDecideDownloadNowTitle1: 'Преимущества',
		helpDecideDownloadNowDesc1: 'Предоставление полного автономного пакета установки с обеспечением до 50 % сжатия и автоматического возобновления загрузки в случае разрыва соединения.',
		helpDecideDownloadNowTitle2: 'Принцип работы',
		helpDecideDownloadNowDesc2: 'Сначала устанавливается небольшой диспетчер загрузок, который обеспечивает оптимизированную загрузку полного пакета установки ПО. После загрузки пакета установки можно начать установку ПО на этом или другом компьютере без подключения к Интернету.',
		helpDecideDownloadNowTitle3: 'Рекомендации',
		helpDecideDownloadNowDesc3: 'Лучший способ установки продуктов Autodesk на другом компьютере или в другое время.',
		helpDecideDownloadNowActionBtn: 'Использовать вариант "Загрузить сейчас"',
		helpDecideDownloadNowAdditionalInfo: 'Дополнительные сведения',
		
		helpDecideBrowserDownloadHeader: 'Загрузка через браузер',
		helpDecideBrowserDownloadTitle1: 'Преимущества',
		helpDecideBrowserDownloadDesc1: 'Хотя этот вариант не требует дополнительного ПО или подключаемых модулей браузера, это наименее эффективный способ доставки ПО, так как он не обеспечивает достаточного сжатия и автоматического возобновления загрузки в отличие от других типов загрузки.',
		helpDecideBrowserDownloadTitle2: 'Принцип работы',
		helpDecideBrowserDownloadDesc2: 'Для получения полного автономного пакета установки используется встроенный в браузер механизм сохранения файлов. После загрузки пакета установки можно начать установку ПО на этом или другом компьютере без подключения к Интернету.',
		helpDecideBrowserDownloadTitle3: 'Рекомендации',
		helpDecideBrowserDownloadDesc3: 'Этот способ рекомендуется, только если нет возможности установить Autodesk Download Manager.',
		helpDecideBrowserDownloadActionBtn: 'Использовать вариант "Загрузка через браузер"',
		helpDecideBrowserDownloadAdditionalInfo: 'Дополнительные сведения',

		splitbtnInstallNow: 'Install Now',
		splitbtnDownloadNow: 'Загрузить сейчас',
		splitbtnBrowserDownload: 'Загрузка через браузер',
		splitbtnHelpDecide: 'Помощь с выбором'	
		},
		'sv-SE':{
		installInstHeader:'Installationsanvisningar',
		installStep1:'När dialogrutan "Save or Run File" visas väljer du "Run"',
		installStep2:'Följ stegen i installationsguiden.',
		installStep3:'Om du får en varning i webbläsaren väljer du "Allow" (vi rekommenderar att du stänger av den här varningen för framtida hämtningar från Autodesk).',
		installStep4:'Hämtningshanteraren för Autodesk är nu klar och kommer automatiskt att börja leverera det du har valt.',
		installFooter:'Har du problem? <a href="http://www.autodesk.com/">Manually start the download</a>',
		installInstMessage: 'För den här hämtningen krävs det att hämtningshanteraren för Autodesk installeras. Slutför följande steg för att hämta och köra det lilla verktyget så att du kan fortsätta.',
		installUpgmessage: 'En ny version av hämtningshanterare för Autodesk behöver installeras. Slutför följande steg för att hämta och köra den lilla uppdateringen så att du kan fortsätta.',
		installAdditionalInfo: 'Ytterligare information',
		installUpgHeader: 'Uppgraderingsanvisningar',

		helpDecideHeader: 'Hjälp mig att välja vilken typ jag ska hämta',
		helpDecideInstallNowHeader: 'Installera nu',
		helpDecideInstallNowTitle1: 'Fördelar',
		helpDecideInstallNowDesc1: 'Det bästa sättet att snabbt komma igång på den här datorn. Hämtning och installation tar mindre än hälften av tiden jämfört med hämtning via webbläsare och påföljande installation. Erbjuder produktval före hämtning, hög komprimering och automatisk återupptagande av hämtning efter anslutningsavbrott.',
		helpDecideInstallNowTitle2: 'Vad händer',
		helpDecideInstallNowDesc2: 'Installationsprogrammet startar direkt och hämtar den programvara du valde under installationsprocessen. Bara den programvara du väljer kommer att installeras. Du kan när som helst gå tillbaka och installera ytterligare programvara.',
		helpDecideInstallNowTitle3: 'Rekommenderas för',
		helpDecideInstallNowDesc3: 'Bästa alternativet för installation av Autodesk-produkter direkt på den här datorn.',
		helpDecideInstallNowActionBtn: 'Använd Installera nu',
		helpDecideInstallNowAdditionalInfo: 'Ytterligare information',
		
		helpDecideDownloadNowHeader: 'Hämta nu',
		helpDecideDownloadNowTitle1: 'Fördelar',
		helpDecideDownloadNowDesc1: 'Levererar ett fullständigt fristående installationspaket med upp till 50 % komprimering och automatisk återupptagning av hämtning efter anslutningsavbrott.',
		helpDecideDownloadNowTitle2: 'Vad händer',
		helpDecideDownloadNowDesc2: 'Först installeras en liten hämtningshanterare och optimerad hämtning aktiveras för det fullständiga installationspaketet för programvaran. När installationspaketet har hämtats kan du påbörja installationen av programvaran på den här datorn utan ytterligare anslutning till Internet.',
		helpDecideDownloadNowTitle3: 'Rekommenderas för',
		helpDecideDownloadNowDesc3: 'Bästa alternativet för installation av Autodesk-produkter på en annan dator eller vid en annan tidpunkt.',
		helpDecideDownloadNowActionBtn: 'Använd Hämta nu',
		helpDecideDownloadNowAdditionalInfo: 'Ytterligare information',
		
		helpDecideBrowserDownloadHeader: 'Hämtning via webbläsare',
		helpDecideBrowserDownloadTitle1: 'Fördelar',
		helpDecideBrowserDownloadDesc1: 'Eftersom det här alternativet fungerar utan ytterligare programvara eller plugin-program för webbläsare är det det minst effektiva alternativet för leverans. I alternativet saknas både den överlägsna komprimeringen och den automatiska hämtningsåterupptagningen som ingår i de andra typerna av hämtning.',
		helpDecideBrowserDownloadTitle2: 'Vad händer',
		helpDecideBrowserDownloadDesc2: 'Använder den inbyggda mekanismen i webbläsaren för att spara filer så att ett fullständigt fristående installationspaket kan levereras. När installationspaketet har hämtats kan du påbörja installationen av programvaran på den här eller någon annan dator utan ytterligare anslutning till Internet.',
		helpDecideBrowserDownloadTitle3: 'Rekommenderas för',
		helpDecideBrowserDownloadDesc3: 'Vi rekommenderar bara den här metoden om du inte kan installera hämtningshanteraren för Autodesk.',
		helpDecideBrowserDownloadActionBtn: 'Använd Hämtning via webbläsare',
		helpDecideBrowserDownloadAdditionalInfo: 'Ytterligare information',

		splitbtnInstallNow: 'Installera nu',
		splitbtnDownloadNow: 'Hämta nu',
		splitbtnBrowserDownload: 'Hämtning via webbläsare',
		splitbtnHelpDecide: 'Hjälp mig att välja'	
		}
	}
